const $=s=>document.querySelector(s),state={project:null,route:[],projects:[],baseline:null,signs:null,approval:null};
const statusText={draft:'草稿',baseline_frozen:'基线已冻结',needs_remediation:'待整改',ready_for_walkthrough:'待走查',walkthrough_failed:'走查失败',ready_for_approval:'待批准',frozen:'已冻结'};
function requestID(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'请求失败');return data}
function toast(message,bad=false){const el=$('#toast');el.textContent=message;el.style.background=bad?'#8b302a':'#18251d';el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function meta(actor){return {project_id:state.project.project_id,request_id:requestID(),expected_revision:state.project.revision,actor_id:actor||state.project.designer_id}}
function escapeHTML(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function sampleNodes(){return [{id:'ENT',name:'主入口',kind:'entrance',accessible:true},{id:'J1',name:'大厅岔路',kind:'decision',accessible:true},{id:'DEST',name:'服务台',kind:'destination',accessible:true}]}
function sampleEdges(){return [{from:'ENT',to:'J1',accessible:true},{from:'J1',to:'DEST',accessible:true}]}
function sampleSigns(){return [{sign_id:'S-ENT',node_id:'ENT',destination_refs:['DEST'],direction:'straight',display_text:'服务台',visibility_distance_m:12,revision_note:'初版'},{sign_id:'S-J1',node_id:'J1',destination_refs:['DEST'],direction:'right',display_text:'服务台 右转',visibility_distance_m:8,revision_note:'初版'},{sign_id:'S-DEST',node_id:'DEST',destination_refs:['DEST'],direction:'arrive',display_text:'服务台到达',visibility_distance_m:5,revision_note:'初版'}]}
async function loadProjects(){const data=await api('/api/projects');state.projects=data.projects;$('#projectList').innerHTML=data.projects.map(p=>`<button data-id="${escapeHTML(p.project_id)}"><strong>${escapeHTML(p.building_name)}</strong><br><small>${statusText[p.status]||p.status}</small></button>`).join('');document.querySelectorAll('#projectList button').forEach(b=>b.onclick=()=>loadProject(b.dataset.id))}
function filterQuery(){const q=new URLSearchParams();for(const [id,key] of [['severityFilter','severity'],['ruleFilter','rule_code'],['nodeFilter','node_id'],['statusFilter','status']]){const el=$('#'+id);if(el?.value)q.set(key,el.value)}return q.toString()}
async function loadProject(id,filtered=false){const query=filtered?filterQuery():'';state.project=await api(`/api/projects/${encodeURIComponent(id)}${query?'?'+query:''}`);state.route=(state.project.walkthrough_route||[]).map(c=>({...c,visible:true,direction_correct:true,note:''}));state.baseline=null;state.signs=null;state.approval=null;render();await loadTimeline()}
function render(){const p=state.project;$('#emptyState').hidden=true;$('#projectView').hidden=false;$('#buildingName').textContent=p.building_name;$('#projectMeta').textContent=`${p.project_id} · 设计员 ${p.designer_id} · 复核员 ${p.reviewer_id}`;$('#statusBadge').textContent=statusText[p.status]||p.status;$('#revision').textContent=`Revision ${p.revision}`;$('#nodesInput').value=JSON.stringify(p.survey.nodes?.length?p.survey.nodes:sampleNodes(),null,2);$('#edgesInput').value=JSON.stringify(p.survey.edges?.length?p.survey.edges:sampleEdges(),null,2);$('#signsInput').value=JSON.stringify(p.signs?.length?p.signs:sampleSigns(),null,2);$('#reviewerInput').value=p.reviewer_id;renderIssues();renderRoute();renderWalkthroughHistory();renderPackage();const frozen=p.status==='frozen';$('#freezeBaseline').disabled=p.status!=='draft';$('#saveSigns').disabled=frozen||!['baseline_frozen','needs_remediation','walkthrough_failed'].includes(p.status);$('#validateRules').disabled=frozen||!['baseline_frozen','needs_remediation'].includes(p.status);$('#reverify').disabled=frozen||!['needs_remediation','walkthrough_failed'].includes(p.status);$('#submitWalkthrough').disabled=p.status!=='ready_for_walkthrough';$('#approvalPreflight').disabled=p.status!=='ready_for_approval';$('#freezePackage').disabled=p.status!=='ready_for_approval';$('#verifyPackage').disabled=!frozen;$('#downloadPackage').disabled=!frozen;$('#baselinePreflight').hidden=true;$('#signPreflight').hidden=true;$('#approvalResult').hidden=true;document.querySelectorAll('#projectList button').forEach(b=>b.classList.toggle('active',b.dataset.id===p.project_id))}
function renderIssues(){const summary=state.project.issue_summary||{};$('#issueSummary').textContent=`未解决 ${summary.unresolved_count||0} · 受影响目的地 ${summary.affected_destination_count||0}`;const list=$('#issueList');list.innerHTML=(state.project.issues||[]).map(i=>{const impact=i.impact||{},paths=(impact.paths||[]).map(x=>x.join(' → ')).join('；')||'无可用路径';const history=(i.evidence_history||[]).map(v=>`<li>版本 ${v.version} · ${escapeHTML(v.submitted_by)} · 方案修订 ${v.sign_revision} · ${v.valid?'有效':'待重新确认'}<br>${escapeHTML(v.resolution)} / ${escapeHTML(v.evidence)}${v.invalid_reason?`<br>${escapeHTML(v.invalid_reason)}`:''}</li>`).join('');return `<div class="issue" data-issue="${escapeHTML(i.issue_id)}"><div class="issue-head"><div><strong>${escapeHTML(i.severity)} · ${escapeHTML(i.rule_code)}</strong> · ${escapeHTML(i.node_id)}<br><small>${escapeHTML(i.issue_id)}</small></div><span class="${i.status==='open'?'tag-error':''}">${i.status==='open'?'未解决':'已关闭'}</span></div><div class="impact">入口：${escapeHTML((impact.entrance_ids||impact.checked_entrances||[]).join(', ')||'无')}<br>目的地：${escapeHTML((impact.destination_ids||[]).join(', ')||'无')}<br>路径：${escapeHTML(paths)}</div>${history?`<ol class="history">${history}</ol>`:''}${(i.reverify_reasons||[]).length?`<div class="tag-error">${escapeHTML(i.reverify_reasons.join('；'))}</div>`:''}${i.status==='open'?`<div class="issue-fields"><input class="resolution" placeholder="处置结论"><input class="evidence" placeholder="证据摘要"><button class="resolve">记录整改</button></div>`:''}</div>`}).join('')||'<p>当前筛选范围没有规则问题。</p>';document.querySelectorAll('.resolve').forEach(b=>b.onclick=()=>resolveIssue(b.closest('.issue')))}
function renderRoute(){const route=state.route;$('#routeList').innerHTML=route.map((c,i)=>`<div class="checkpoint"><strong>${i+1}. ${escapeHTML(c.node_id)}</strong><div class="checkpoint-main"><span><label><input type="checkbox" data-index="${i}" data-field="visible" checked> 可见</label>　<label><input type="checkbox" data-index="${i}" data-field="direction_correct" checked> 方向正确</label></span><input class="failure-note" data-index="${i}" placeholder="失败原因"></div></div>`).join('')||'<p>当前没有待走查站点。</p>'}
function renderWalkthroughHistory(){const rows=(state.project.walkthroughs||[]).map(r=>`<div class="walk-round"><strong>第 ${r.round||1} 轮 · ${r.targeted?'定向复验':'完整走查'} · ${r.decision==='pass'?'通过':'失败'}</strong><br><small>${escapeHTML(r.review_id)}${r.parent_review_id?' · 来源 '+escapeHTML(r.parent_review_id):''} · 失败站点 ${(r.failed_checkpoint_ids||[]).map(escapeHTML).join(', ')||'无'}</small></div>`).join('');$('#walkthroughHistory').innerHTML=rows}
function renderPackage(){const p=state.project.package;$('#packageInfo').textContent=p?JSON.stringify({package_id:p.package_id,source_revision:p.source_revision,sha256_digest:p.sha256_digest,approved_by:p.approved_by,frozen_at:p.frozen_at},null,2):'尚未冻结';$('#verificationResult').hidden=true}
async function loadTimeline(){if(!state.project)return;const data=await api(`/api/projects/${state.project.project_id}/timeline`);$('#timelineList').innerHTML=data.events.map(e=>`<div class="event"><strong>${escapeHTML(e.type)}</strong> · Revision ${e.revision}<br><small>${new Date(e.at).toLocaleString()} · ${escapeHTML(e.actor_id)} · ${escapeHTML(e.digest.slice(0,16))}</small></div>`).join('')}
async function mutate(path,method,body){try{const result=await api(path,{method,body:JSON.stringify(body)});toast(result.message||'操作完成');await loadProjects();await loadProject(state.project?.project_id||result.project_id);return result}catch(e){toast(e.message,true);throw e}}
function surveyInput(){const nodes=JSON.parse($('#nodesInput').value),edges=JSON.parse($('#edgesInput').value);return {nodes,edges,entrance_ids:nodes.filter(n=>n.kind==='entrance').map(n=>n.id),destination_ids:nodes.filter(n=>n.kind==='destination').map(n=>n.id),accessible_edge_flags:Object.fromEntries(edges.map(e=>[`${e.from}->${e.to}`,!!e.accessible]))}}
function showResult(selector,html,bad=false){const el=$(selector);el.hidden=false;el.classList.toggle('bad',bad);el.innerHTML=html}
$('#freezeBaseline').onclick=async()=>{try{const survey=surveyInput(),key=JSON.stringify(survey);if(!state.baseline||state.baseline.key!==key){const pre=await api(`/api/projects/${state.project.project_id}/baseline/preflight`,{method:'POST',body:JSON.stringify({survey})});state.baseline={key,pre};showResult('#baselinePreflight',`节点 ${pre.stats.node_count} · 连接 ${pre.stats.edge_count} · 入口 ${pre.stats.entrance_count} · 目的地 ${pre.stats.destination_count} · 阻断 ${pre.stats.blocker_count}<br>${pre.blockers.map(x=>escapeHTML(`${x.code}：${x.message}`)).join('<br>')||'预检通过'}`,pre.blockers.length>0);$('#freezeBaseline').textContent=pre.blockers.length?'重新预检':'确认冻结';return}if(state.baseline.pre.blockers.length)return;await mutate(`/api/projects/${state.project.project_id}/baseline`,'POST',{meta:meta(),survey})}catch(e){toast(e.message,true)}};
$('#saveSigns').onclick=async()=>{try{const signs=JSON.parse($('#signsInput').value),key=JSON.stringify(signs);if(!state.signs||state.signs.key!==key){const pre=await api(`/api/projects/${state.project.project_id}/signs/preflight`,{method:'POST',body:JSON.stringify({signs})});state.signs={key,pre};const d=pre.diff;showResult('#signPreflight',`新增 ${d.added.length}：${escapeHTML(d.added.join(', ')||'无')}<br>修改 ${d.modified.length}：${escapeHTML(d.modified.join(', ')||'无')}<br>删除 ${d.deleted.length}：${escapeHTML(d.deleted.join(', ')||'无')}<br>未变化 ${d.unchanged.length}${pre.errors.length?'<br>'+pre.errors.map(x=>escapeHTML(`${x.sign_id||'#'+x.index}：${x.message}`)).join('<br>'):''}`,pre.errors.length>0);$('#saveSigns').textContent=pre.errors.length?'重新预检':'确认保存';return}if(state.signs.pre.errors.length)return;await mutate(`/api/projects/${state.project.project_id}/signs`,'PUT',{meta:meta(),signs})}catch(e){toast(e.message,true)}};
$('#validateRules').onclick=()=>mutate(`/api/projects/${state.project.project_id}/validate`,'POST',{meta:meta()});
async function resolveIssue(el){await mutate(`/api/projects/${state.project.project_id}/issues/${el.dataset.issue}/resolve`,'POST',{meta:meta(),issue_id:el.dataset.issue,resolution:el.querySelector('.resolution').value,evidence:el.querySelector('.evidence').value,updated_signs:JSON.parse($('#signsInput').value)})}
$('#reverify').onclick=()=>mutate(`/api/projects/${state.project.project_id}/reverify`,'POST',{meta:meta()});
$('#submitWalkthrough').onclick=()=>{const route=state.route.map(c=>({...c}));document.querySelectorAll('#routeList input[type=checkbox]').forEach(i=>route[+i.dataset.index][i.dataset.field]=i.checked);document.querySelectorAll('#routeList .failure-note').forEach(i=>route[+i.dataset.index].note=i.value);return mutate(`/api/projects/${state.project.project_id}/walkthrough`,'POST',{meta:meta($('#reviewerInput').value),checkpoints:route})};
$('#approvalPreflight').onclick=async()=>{try{const actor=$('#reviewerInput').value,pre=await api(`/api/projects/${state.project.project_id}/approval-preflight?approver_id=${encodeURIComponent(actor)}`);state.approval=pre;showResult('#approvalResult',`源修订 ${pre.source_revision} · 路径 ${pre.path_count} · 标识 ${pre.sign_count} · 处置版本 ${pre.disposition_count} · 走查 ${pre.walkthrough_rounds}<br>候选摘要 ${escapeHTML(pre.candidate_digest)}${pre.blockers.length?'<br>'+pre.blockers.map(escapeHTML).join('<br>'):'<br>批准预检通过'}`,pre.blockers.length>0)}catch(e){toast(e.message,true)}};
$('#freezePackage').onclick=async()=>{if(!state.approval){await $('#approvalPreflight').onclick();toast('请核对批准预检后再次确认');return}if(state.approval.blockers.length){toast('批准预检仍有阻断项',true);return}return mutate(`/api/projects/${state.project.project_id}/freeze`,'POST',{meta:meta($('#reviewerInput').value),source_revision:state.approval.source_revision,candidate_digest:state.approval.candidate_digest})};
$('#verifyPackage').onclick=async()=>{try{const x=await api(`/api/projects/${state.project.project_id}/package/verify`,{method:'POST',body:'{}'}),v=x.verification;showResult('#verificationResult',`核验时间 ${new Date(v.checked_at).toLocaleString()}<br>摘要 ${v.summary.passed?'通过':'失败'}：${escapeHTML((v.summary.failures||[]).join('；'))}<br>结构 ${v.structure.passed?'通过':'失败'}：${escapeHTML((v.structure.failures||[]).join('；'))}<br>业务 ${v.business.passed?'通过':'失败'}：${escapeHTML((v.business.failures||[]).join('；'))}<br>事件链 ${v.event_chain.passed?'通过':'失败'}：${escapeHTML((v.event_chain.failures||[]).join('；'))}`,!x.valid);toast(x.valid?'深度核验通过':'深度核验未通过',!x.valid)}catch(e){toast(e.message,true)}};
$('#downloadPackage').onclick=()=>window.location=`/api/projects/${state.project.project_id}/package`;
for(const id of ['severityFilter','ruleFilter','statusFilter'])$('#'+id).onchange=()=>loadProject(state.project.project_id,true);$('#nodeFilter').onchange=()=>loadProject(state.project.project_id,true);$('#clearFilters').onclick=()=>{for(const id of ['severityFilter','ruleFilter','nodeFilter','statusFilter'])$('#'+id).value='';loadProject(state.project.project_id)};
for(const id of ['nodesInput','edgesInput'])$('#'+id).oninput=()=>{state.baseline=null;$('#freezeBaseline').textContent='预检基线'};$('#signsInput').oninput=()=>{state.signs=null;$('#saveSigns').textContent='预检方案'};$('#reviewerInput').oninput=()=>{state.approval=null;$('#approvalResult').hidden=true};
$('#newProject').onclick=()=>$('#createDialog').showModal();$('#createSubmit').onclick=async e=>{e.preventDefault();const id=$('#newID').value.trim();try{const result=await api('/api/projects',{method:'POST',body:JSON.stringify({meta:{project_id:id,request_id:requestID(),expected_revision:0,actor_id:$('#newDesigner').value.trim()},building_name:$('#newBuilding').value.trim(),zones:$('#newZones').value.split(',').map(x=>x.trim()).filter(Boolean),designer_id:$('#newDesigner').value.trim(),reviewer_id:$('#newReviewer').value.trim()})});$('#createDialog').close();await loadProjects();await loadProject(result.project_id);toast('项目已创建')}catch(err){toast(err.message,true)}};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
loadProjects().catch(e=>toast(e.message,true));
